spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.136.207:3306/blog-extensions?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: xxx
  redis:
    host: xxx

#eureka:
#  client:
#    service-url:
#      defaultZone: http://39.108.136.207:8686/eureka/
#  instance:
#    prefer-ip-address: true
