spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx/blog-extensions?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: xx
  redis:
    host: xx

#ribbon:
#  ReadTimeout: 6000000000
#  ConnectTimeout: 6000000000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://xx/eureka/
#  instance:
#    prefer-ip-address: true
