server:
  port: 9002
spring:
  profiles:
    active: dev
  application:
    name: blog-server #指定服务名

# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: pers.fjl.common.po
  global-config:
    #    db-config:
    #      table-prefix: t_
    id-type: 1  #0:数据库ID自增   1:用户输入id
    #    db-column-underline: false
    #    db-config:
    #          table-underline=false:
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
