spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xx/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: xx
  redis:
    host: xx

logging:
  level:
    root: warn
    pers.fjl.server: debug
  file:
    path: log/blog-prod.log

ribbon:
  ReadTimeout: 600000000
  ConnectTimeout: 600000000

eureka:
  client:
    service-url:
      defaultZone: http://xx/eureka/
  instance:
    prefer-ip-address: true
