server:
  port: 9002
  servlet:
    session:
      timeout: 3600
spring:
  profiles:
    active: dev
  application:
    name: blog-server #指定服务名
  mail:
    host: smtp.qq.com
    username: 1626680964@qq.com
    password:
    default-encoding: UTF-8
#    port: 587
#    properties:
#      mail:
#      smtp:
#      auth: true
#      socketFactory:
#      class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    username: guest
    password: guest
    host: ip
    port: 5672
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: ip:9300
      repositories:
        enabled: true
es:
  host: ip

# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: pers.fjl.common.po
  global-config:
    #    db-config:
    #      table-prefix: t_
    id-type: 1  #0:数据库ID自增   1:用户输入id
    #    db-column-underline: false
    #    db-config:
    #          table-underline=false:
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 上传模式
upload:
  mode: oss
  local:
    url:
    path:
  oss:
    file:
      url:
      bucketName:
      endpoint:
      keyId:
      keySecret:

face:
  group-id:


#第三方配置信息
qq:
  app-id:
  app_KEY:
  redirect_URI :
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

weibo:
  app-id:
  app-secret:
  grant-type: authorization_code
  redirect-url:
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}

pay:
  appId:
  appSecret:
  notifyUrl:
  returnUrl:
